### ISSUE TITLE
GET coin sends coins for all users

### ISSUE THREAD

**Issue by tgflynn** [deginner/swagxample#4]
I'm not sure if you are interested in security bugs in swagxample but if this is intended to be used as an example by users of the libraries I would suggest fixing this.

The function server.py:get_coins does nothing to restrict the list of coins retrieved from the database to those owned by the logged in user.

The following client code (modified from ctf1.py) creates a new user and then using the new user's credentials returns all coins in the database, regardless of owner :

##### Example of generating bitjws key to use for communicating with the server.
import bitjws
privkey = bitjws.PrivateKey()

my_pubkey = privkey.pubkey.serialize()
my_address = bitjws.pubkey_to_addr(my_pubkey)
print "Created bitjws (Bitcoin) address %s" % my_address

##### Example User registration using bravado-bitjws client
# https://github.com/deginner/bravado-bitjws
from bravado_bitjws.client import BitJWSSwaggerClient

host = "swagxample.deginner.com"
url = "http://swagxample.deginner.com/"
specurl = "%sstatic/swagger.json" % url
username = str(my_address)[0:8]

client = BitJWSSwaggerClient.from_url(specurl, privkey=privkey)

luser = client.get_model('User')(username=username)
user = client.user.addUser(user=luser).result()

print "registered as user\n%s" % user

coins = client.coin.findCoin().result()

print "coins:", coins

**Comment by isysd** [comment]
That is a good point. The sole purpose of swagxample is for demonstration. If the app functionality doesn't follow a basic security model like forks will, then it doesn't fulfill it's purpose. I will work on the coin collection functionality to make it more realistic.

For the purpose of the [competition](https://github.com/deginner/swagxample/wiki/Capture-The-Flag-Game-1), however, this does not affect anything. The contents of the app and database are arbitrary messages. It is the server's signing key that is secret.

**Comment by isysd** [comment]
@marcoagner please fix this, so that it restricts the returned Coin list to those owned by the signing User. This restricted permission model is the one we want to use with SockJS, so we might as well be consistent with our examples and tests.
